language: ruby
dist: trusty
sudo: required
cache: bundler
rvm:
  - 2.4.4

env:
  global:
    - JASMINE_BROWSER=firefox
    - MOZ_HEADLESS=1

addons:
  mariadb: '10.2'
  firefox: latest
  
services:
  - mysql

before_install:
  - gem install bundler
  - sudo apt-get install software-properties-common
  - sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
  - sudo add-apt-repository -y 'deb [arch=amd64,i386,ppc64el] http://nyc2.mirrors.digitalocean.com/mariadb/repo/10.2/ubuntu trusty main'
  - sudo add-apt-repository -y ppa:builds/sphinxsearch-rel22
  - sudo apt-get -qq update
  - sudo apt-get install -y libmariadb-dev libmariadbclient18 sphinxsearch
  - sudo sh -c 'curl -sSL https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz | tar -C /usr/local/bin/ -xzf - geckodriver'

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/lilsis.yml.sample config/lilsis.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - mysql -e 'CREATE DATABASE littlesis_test;'

script:
  - RAILS_ENV=test bundle exec rake db:structure:load
  - RAILS_ENV=test bundle exec rake mysql:travis_definer_fix
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test COVERAGE=true bundle exec rspec
  - RAILS_ENV=test bundle exec rake jasmine:ci
